### ISSUE TITLE
Cannot reproduce this experiment

### ISSUE THREAD

**Issue by Polynomia** [openai/finetune-transformer-lm#15]
Hi,

I tried to run this code to reproduce the accuracy of 85%. But I have executed 3 times and got only 53% accuracy each time.
Could you please tell me some tips about the instructions to run this code or set parameters?
I did't change any code and used the command `python train.py --dataset rocstories --desc rocstories --submit --analysis --data_dir [path to data here]` in readme. 

Thanks

**Comment by Franck-Dernoncourt** [comment]
I get accuracy of ~85% on ROC 2016 without having to change any parameters aside from `--n_gpu`, which I set to 1, just because I wanted to use only 1 GPU (if `--n_gpu 2`, then the default training batch size is 8x2=16, which caused out of memory issues on my GTX 1080).

**Comment by Polynomia** [comment]
Thank you so much for your reply. 
I got 87% after I set `n_gpu` to 1. I think there may be a problem in implementation of multi-gpu. I test default `n_gpu` = 4 on a server with 8 Tesla K80 4 times but only get 53%.

**Comment by wykdg** [comment]
i got 53% in python2.7 with tensorflow 1.2，while 87% with python 3.6 and tensorflow 1.6.maybe you should check the version of tensorflow

**Comment by Newmu** [comment]
This looks to have been due to an implementation difference between python 2 and python 3. Only python 3 is supported but I've removed the code that was likely causing this issue as discussed in #21
