### ISSUE TITLE
Convolution layer filter width

### ISSUE THREAD

**Issue by sharpsy** [openai/finetune-transformer-lm#16]
In the code that does the convolution, there is a separate implementation for convolution with filter width of 1 and convolution with other filter widths.

Convolution with a filter width of 1 is special cased due to a faster implementation and it is the only filter width used by the current code. Other implementation has a comment `#was used to train LM`.

Does it mean that a different convolution filter width was used for language modeling or was it just using a less efficient implementation but with the same filter width?

**Comment by Newmu** [comment]
Less efficient implementation of the same thing!
