### ISSUE TITLE
help to understand bpe logic 

### ISSUE THREAD

**Issue by BogdanDidenko** [openai/finetune-transformer-lm#24]
Hello. Sorry, but i can't understand how this function work. In my tests in most cases the result is equal to original token parameter value. 
https://github.com/openai/finetune-transformer-lm/blob/master/text_utils.py#L49

**Comment by madisonmay** [comment]
BPE stands for byte-pair encoding: a read over https://arxiv.org/abs/1508.07909 may be helpful.
