### ISSUE TITLE
Where can I get these two datasets?

### ISSUE THREAD

**Issue by ghost** [openai/finetune-transformer-lm#41]
`def rocstories(data_dir, n_train=1497, n_valid=374):
    storys, comps1, comps2, ys = _rocstories(os.path.join(data_dir, 'cloze_test_val__spring2016 - cloze_test_ALL_val.csv'))
    teX1, teX2, teX3, _ = _rocstories(os.path.join(data_dir, 'cloze_test_test__spring2016 - cloze_test_ALL_test.csv'))`

**Comment by rodgzilla** [comment]
You can get the datasets from this [website](http://cs.rochester.edu/nlp/rocstories/).

**Comment by ghost** [comment]
I've tried to click 'this form', but the link provided(https://goo.gl/forms/aQz39sdDrO) is somehow unreachable.

**Comment by rodgzilla** [comment]
You will receive links to the dataset by email.

**Comment by ghost** [comment]
The link works by changing another browser.Thanks!
